spring.application.name=RateLimiter
spring.application.name=RateLimiter

rate-limit.endpoints.general.path=/api/general
rate-limit.endpoints.general.limit=20
rate-limit.endpoints.general.window-size-in-seconds=60

rate-limit.endpoints.submit.path=/api/submit
rate-limit.endpoints.submit.limit=5
rate-limit.endpoints.submit.window-size-in-seconds=60

rate-limit.endpoints.status.path=/api/status
rate-limit.endpoints.status.limit=60
rate-limit.endpoints.status.window-size-in-seconds=60

rate-limit.cleanup-interval-ms=60000
